source 'https://rubygems.org' do
  gem 'cuba', '3.9.2'
  gem 'mote', '1.3.0'
  gem 'redcarpet', '3.4.0'
  gem 'sass', '3.5.6'
  gem 'mote-render', '1.1.0'
  gem 'shotgun', '0.9.2'
  gem 'tilt', '2.0.8'
  gem 'pygments.rb', '1.2.1'
end
